package com.revature.daoimplemt;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.revature.daos.OrderDAO;
import com.revature.models.Customer;
import com.revature.models.Order;
import com.revature.util.ConnectionUtil;

public class OrderDAOImpl implements OrderDAO {

	private static Logger log = LogManager.getLogger(CustomerDAOImpl.class);

	@Override
	public Order createOrder(Order order) {
		String sql = "insert into orders (customer_id, menu_id, flavor1_id, flavor2_id) values (?,?,?,?) returning order_id;";
		try (Connection c = ConnectionUtil.getConnectionFromEnv()) {
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setInt(1, order.getCustomerId());
			ps.setInt(2, order.getItem_id());
			ps.setInt(3, order.getFlavor1_id());
			ps.setInt(4, order.getFlavor2_id());

			ResultSet rs = ps.executeQuery(); // return the id generated by the database
			if (rs.next()) {
				order.setOrderId(rs.getInt("order_id"));
			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return order;
	}

	@Override
	public Order retrieveOrderById(int id) {
		String sql = "select * from orders where order_id = ?;";
		Order order = null;

		try (Connection c = ConnectionUtil.getConnectionFromEnv();) {
			PreparedStatement ps = c.prepareStatement(sql);

			ps.setInt(1, id); // this refers to the 1st "?" in the sql string, allows to inject data

			ResultSet rs = ps.executeQuery();

			while (rs.next()) {
				order = new Order();
				order.setOrderId(rs.getInt("order_id"));
				order.setCustomerId(rs.getInt("customer_id"));
				order.setItem_id(rs.getInt("menu_id"));
				order.setFlavor1_id(rs.getInt("flavor1_id"));
				order.setFlavor2_id(rs.getInt("flavor2_id"));

			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return order;
	}

	@Override
	public Order retrieveOrderByUsername(String username) {
		String sql = "SELECT * "
				+ "FROM orders o "
				+ "JOIN customers c "
				+ "ON o.customer_id = c.id "
				+ "WHERE c.username  = " + username + ";";
		Order order = null;

		try (Connection c = ConnectionUtil.getConnectionFromEnv();) {
			PreparedStatement ps = c.prepareStatement(sql);

			ResultSet rs = ps.executeQuery();

			while (rs.next()) {
				order = new Order();
				order.setOrderId(rs.getInt("order_id"));
				order.setCustomerId(rs.getInt("customer_id"));
				order.setItem_id(rs.getInt("menu_id"));
				order.setFlavor1_id(rs.getInt("flavor1_id"));
				order.setFlavor2_id(rs.getInt("flavor2_id"));

			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return order;
	}

	@Override
	public boolean updateOrder(Order order, int id) {
		String sql = "UPDATE orders SET customer_id = ?, menu_id = ?, flavor1_id = ?, flavor2_id = ? WHERE order_id = ?;";
		int rowsChanged = -1;

		try (Connection c = ConnectionUtil.getConnectionFromEnv()) {
			PreparedStatement ps = c.prepareStatement(sql);

			ps.setInt(1, order.getCustomerId());
			ps.setInt(2, order.getItem_id());
			ps.setInt(3, order.getFlavor1_id());
			ps.setInt(4, order.getFlavor2_id());
			ps.setInt(5, order.getOrderId());

			rowsChanged = ps.executeUpdate();

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		if (rowsChanged < 1) {
			return false;
		}
		return true;
	}

	@Override
	public void deleteOrderById(int id) {
		String sql = "DELETE FROM orders WHERE order_id = ?;";

		try (Connection c = ConnectionUtil.getConnectionFromEnv()) {
			PreparedStatement ps = c.prepareStatement(sql);

			ps.setInt(1, id);

			ResultSet rs = ps.executeQuery();

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}
